import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/context/AuthContext";
// import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

export const metadata: Metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

// const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        {/* <QueryClientProvider client={queryClient}> */}
        <body>
          <Navbar />
          {children}
        </body>
        {/* </QueryClientProvider> */}
      </AuthProvider>
    </html>
  );
}
